language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
os:
  - linux
  - osx

install:
  - echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION"
  - bash .travis/install_python.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate test-env
  - pip install coveralls
  - if [[ "$TRAVIS_PYTHON_VERSION" == 3.* ]]; then
      bash .travis/convert_to_python_3.sh;
    fi
  - python setup.py install

script: 
  - (cd docs && make html)
  - nosetests --with-coverage --cover-package=landlab

virtualenv:
  system_site_packages: false

after_success:
  coveralls
