language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install: "pip install -r requirements.txt"

script: nosetests

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-numpy python-scipy

