env:
  - TRAVIS_PYTHON_VERSION="2.6" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="2.7" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="2.7" NUMPY_VERSION="1.10"
  - TRAVIS_PYTHON_VERSION="3.3" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="3.4" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="3.4" NUMPY_VERSION="1.10"
os:
- linux
- osx
matrix:
  allow_failures:
    - os: osx
      env: TRAVIS_PYTHON_VERSION="2.6" NUMPY_VERSION="1.9"
sudo: false
install:
- echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION"
- bash .ci/travis/install_python.sh
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate test-env
- pip install coveralls
- conda install numpy=$NUMPY_VERSION
- conda install scipy
- python setup.py install
script:
- (cd docs && make html 2> /dev/null)
- bash .ci/travis/run_travis_test.sh
virtualenv:
  system_site_packages: false
after_success: coveralls
deploy:
  provider: pypi
  user: mcflugen
  password:
    secure: "gb0S9ei9RkXM5sKke4HOC0u0/g63Qd7pq+uSFURavq9szrt3vfRkDZMnRiC/8G1NJ6xuWzPugJdU3yRtJPp6lCvjwFVb4M9PY1TFkvQ5bcqy9c9OF5kCmjrKaCvK9uTmB5getn1Xnp6DX97LUXB2fB25AOKoKQlRXro2k0713IY="
  on:
    tags: true
    repo: landlab/landlab
  distributions: "sdist bdist_wheel"
notifications:
  slack:
    secure: gRKbqjPgp0ZcFtecHOwjLAFbzzBr2zyFrxk7OAS/cea/9U8bLQNA0jZs3ZHtAgR53gdnFlx/GI10d/KD9XMKU55gQkO4FSvfYMK7Xzs2tfnEa5flTqQKRfjB1oJ2fmb81yshUe+xKsXBoedP7SPYv2mutMOY8srKwUcuE0yGmAw=
