env:
  - TRAVIS_PYTHON_VERSION="2.6" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="2.7" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="2.7" NUMPY_VERSION="1.10"
  - TRAVIS_PYTHON_VERSION="3.3" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="3.4" NUMPY_VERSION="1.9"
  - TRAVIS_PYTHON_VERSION="3.4" NUMPY_VERSION="1.10"
os:
- linux
- osx
matrix:
  exclude:
    - os: osx
      env: TRAVIS_PYTHON_VERSION="2.6"
sudo: false
install:
- echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION"
- bash .ci/travis/install_python.sh
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate test-env
- pip install coveralls
- conda install numpy=$NUMPY_VERSION
- python setup.py install
script:
- (cd docs && make html 2> /dev/null)
- bash .ci/travis/run_travis_test.sh
virtualenv:
  system_site_packages: false
after_success: coveralls
deploy:
  provider: pypi
  user: landlab
  password:
    secure: Ba/spYvhJuoXB9Kv78xwU2AMEcQe4USIbSX5S2d8ytmjKNFwYSOGZ8W4snyoq/txkPhaz97joKp8uFJd0YITf6A6feP5vEatZWKQQ8qKf68eo9AaK+vSxUQuoPBnEt0EZ/l/77t6XYWtYCB2+m6jD8/rxO2x+LG9PQ3IBk80sNQ=
  on:
    tags: true
    repo: landlab/landlab
notifications:
  slack:
    secure: gRKbqjPgp0ZcFtecHOwjLAFbzzBr2zyFrxk7OAS/cea/9U8bLQNA0jZs3ZHtAgR53gdnFlx/GI10d/KD9XMKU55gQkO4FSvfYMK7Xzs2tfnEa5flTqQKRfjB1oJ2fmb81yshUe+xKsXBoedP7SPYv2mutMOY8srKwUcuE0yGmAw=
