language: python
python:
  - "2.6"
  - "2.7"

install: "pip install -r requirements.txt"

script: nosetests

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq python-scipy=0.13.3-2 python-numpy

